import { useEffect, useMemo, useState } from 'react'
import {
  ArrowDownRight,
  ArrowUpRight,
  BookOpen,
  Calculator as CalculatorIcon,
  Check,
  ChevronRight,
  CircleDollarSign,
  Gauge,
  LockKeyhole,
  Menu,
  MoveUpRight,
  Play,
  Sparkles,
  Target,
  WalletCards,
  X,
} from 'lucide-react'
import ExpandableProfileCardDemo from './ExpandableProfileCardDemo.jsx'
import { courseLessons, lessonForSlug } from './courseContent.js'

const lessons = courseLessons.map((lesson) => ({ ...lesson, topic: lesson.category === 'Markets' ? 'markets' : lesson.category === 'Investing' ? 'investing' : 'basics', meta: `${lesson.category} · ${lesson.minutes} min read`, text: lesson.standfirst }))

function formatINR(value) { return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 }).format(value) }
function go(to) { window.location.hash = to }
function LinkButton({ to, children, className = '', icon = true }) { return <button className={className} onClick={() => go(to)}>{children}{icon && <ArrowUpRight size={16} strokeWidth={2.5} />}</button> }

function Header({ page }) {
  const [open, setOpen] = useState(false)
  const links = [['home', 'Home'], ['lessons', 'Lessons'], ['calculator', 'Calculator']]
  return <header className="site-header"><div className="header-inner">
    <a className="brand" href="#home"><span className="brand-mark"><CircleDollarSign size={20} /></span><span>mintify</span></a>
    <button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X size={20} /> : <Menu size={20} />}</button>
    <nav className={open ? 'is-open' : ''} aria-label="Main navigation">{links.map(([key, label]) => <a key={key} className={page === key ? 'active' : ''} href={`#${key}`} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-button" href="#lessons" onClick={() => setOpen(false)}>Start learning <ArrowUpRight size={15} /></a></nav>
  </div></header>
}

function Footer() { return <footer><div className="footer-inner"><div><a className="brand" href="#home"><span className="brand-mark"><CircleDollarSign size={20} /></span><span>mintify</span></a><p className="footer-note">Friendly financial education for Indian teens. For learning only, not personal investment advice.</p></div><div className="footer-links"><a href="#lessons">Lessons</a><a href="#calculator">Calculator</a><a href="#about">About</a><a href="#privacy">Privacy</a><a href="#terms">Terms</a></div></div></footer> }

function Orb({ className = '' }) { return <span aria-hidden="true" className={`orb ${className}`} /> }
function Pill({ children, tone = '' }) { return <span className={`pill ${tone}`}>{children}</span> }

function HeroVisual() { return <div className="hero-visual" aria-label="A 3D illustration of a money dashboard">
  <Orb className="orb-one" /><Orb className="orb-two" />
  <div className="orbit orbit-a" /><div className="orbit orbit-b" />
  <div className="dashboard-card card-back"><div className="mini-label">MINTIFY / 01</div><div className="back-lines"><span /><span /><span /></div></div>
  <div className="dashboard-card card-front"><div className="card-top"><span className="mini-label">YOUR MONEY MAP</span><span className="live-dot">LIVE</span></div><div className="balance">₹24,680<span>practice balance</span></div><div className="chart"><span className="chart-fill" /><svg viewBox="0 0 340 110" preserveAspectRatio="none"><path d="M0 92 C30 70 42 84 64 66 S105 76 127 50 S163 60 190 39 S235 53 254 26 S298 43 340 10" /></svg></div><div className="card-bottom"><span><ArrowUpRight size={14} /> 18.4%</span><span>30 day learning streak</span></div></div>
  <div className="floating-chip chip-one"><Sparkles size={15} /><span>learn by doing</span></div><div className="floating-chip chip-two"><Check size={15} /><span>zero jargon</span></div>
</div> }

function Home() { return <main className="page home-page">
  <section className="hero"><div className="hero-copy"><Pill tone="pill-purple"><Sparkles size={13} /> money, but make it make sense</Pill><h1>Learn money like you’re <em>already</em> good at it.</h1><p className="lead">The calm, colorful corner of the internet for Indian teens figuring out stocks, SIPs, taxes, and the rest of the money maze.</p><div className="hero-actions"><LinkButton to="lessons" className="button">Explore the lab</LinkButton><LinkButton to="calculator" className="button secondary">Run a scenario <ChevronRight size={17} /></LinkButton></div><div className="hero-proof"><span className="proof-stack"><i>₹</i><i>↗</i><i>✦</i></span><span><strong>6 short lessons</strong><small>built for the questions you actually ask</small></span></div></div><HeroVisual /></section>
  <section className="signal-strip"><span>NO HYPE</span><span>JUST USEFUL MONEY BITS</span><span>MADE FOR INDIA</span><span>LEARN AT YOUR PACE</span></section>
  <section className="intro-bento"><div className="section-kicker">01 / the mintify method</div><div className="intro-statement"><h2>It’s not a finance bro lecture. <span>It’s a better first step.</span></h2><p>Mintify turns intimidating money words into small, clear moves. No stock-picking. No “become a millionaire” theatre. Just the confidence to understand what’s going on.</p><div className="check-list"><div><Check size={16} /> Plain-language explanations</div><div><Check size={16} /> Examples in rupees, not dollars</div><div><Check size={16} /> The “what this can’t tell you” bit</div></div></div><div className="bento-note note-yellow"><span className="note-icon">01</span><strong>Start with one question.</strong><p>“What even is a demat account?” is a perfectly good place to begin.</p><a href="#lesson-demat">See the answer <ArrowUpRight size={15} /></a></div><div className="bento-note note-lilac"><span className="note-icon">02</span><strong>Leave with a better one.</strong><p>Good financial learning should make you curious, not overwhelmed.</p><a href="#lessons">Find your next read <ArrowUpRight size={15} /></a></div></section>
  <section className="feature-section"><div className="section-heading"><div><div className="section-kicker">02 / pick your entry point</div><h2>Three ways to get unstuck.</h2></div><a href="#lessons" className="text-link">View all lessons <ArrowUpRight size={16} /></a></div><div className="feature-grid"><article className="feature-card feature-lime"><div className="feature-number">01</div><BookOpen size={29} /><h3>Learn the words</h3><p>Demat, NAV, market cap — decode the language that makes money conversations feel less intimidating.</p><a href="#lessons">Browse lessons <ArrowUpRight size={16} /></a></article><article className="feature-card feature-violet"><div className="feature-number">02</div><CalculatorIcon size={29} /><h3>See the numbers</h3><p>Use a simple SIP calculator to understand time, consistency, and why the future is a long game.</p><a href="#calculator">Try the calculator <ArrowUpRight size={16} /></a></article><article className="feature-card feature-orange"><div className="feature-number">03</div><Target size={29} /><h3>Build your instinct</h3><p>Learn the difference between a useful question and a loud opinion. That is a superpower.</p><a href="#about">Why Mintify exists <ArrowUpRight size={16} /></a></article></div></section>
  <section className="terminal-section"><div className="terminal-copy"><div className="section-kicker">03 / one useful habit</div><h2>Money gets easier when you stop trying to know <span>everything.</span></h2><p>Open one lesson. Try one example. Save one useful thought. That’s the whole loop.</p><LinkButton to="lessons" className="button dark-button">Start with a question</LinkButton></div><div className="terminal-window"><div className="terminal-bar"><span /><span /><span /><b>mintify / learning-mode</b></div><div className="terminal-body"><div><i>$</i> mintify <span>--begin</span></div><p>Welcome back, curious human.</p><div><i>›</i> choose_topic <span className="terminal-cursor">_</span></div><div className="terminal-options"><span>01 stocks</span><span>02 SIPs</span><span>03 taxes</span></div><div className="terminal-success"><Check size={15} /> no jargon detected</div></div></div></section>
  <section className="pricing-section"><div className="section-kicker">04 / your pace, your path</div><h2>Pick a learning mode.</h2><p className="pricing-intro">No paywall for the basics. These are playful paths through the same clear ideas.</p><div className="pricing-grid"><article><Pill tone="pill-yellow">curious</Pill><h3>First tab open</h3><p>For the “wait, what is a stock?” moment.</p><div className="price">₹0 <small>forever</small></div><ul><li><Check size={15} /> 6 beginner lessons</li><li><Check size={15} /> SIP calculator</li><li><Check size={15} /> No sign-up</li></ul><a href="#lessons" className="price-link">Start here <ArrowUpRight size={15} /></a></article><article className="pricing-featured"><Pill tone="pill-purple">most useful</Pill><h3>Building the habit</h3><p>For the person who wants a calmer money brain.</p><div className="price">₹0 <small>also forever</small></div><ul><li><Check size={15} /> Guided lesson sequence</li><li><Check size={15} /> Practice scenarios</li><li><Check size={15} /> Monthly refreshers</li></ul><a href="#lessons" className="price-link">Keep going <ArrowUpRight size={15} /></a></article><article><Pill tone="pill-coral">share it</Pill><h3>Explain it forward</h3><p>For friends, siblings, and the group chat.</p><div className="price">∞ <small>good questions</small></div><ul><li><Check size={15} /> Shareable explainers</li><li><Check size={15} /> Classroom-friendly</li><li><Check size={15} /> Better conversations</li></ul><a href="#about" className="price-link">See the why <ArrowUpRight size={15} /></a></article></div></section>
  <section className="quote-band"><div className="quote-mark">“</div><blockquote>It’s not about knowing the answer to everything. It’s about knowing what to ask next.</blockquote><span>— the Mintify rule of thumb</span></section>
</main> }

function Lessons() { const [topic, setTopic] = useState('all'); const filtered = topic === 'all' ? lessons : lessons.filter((lesson) => lesson.topic === topic); return <main className="page"><div className="lesson-heading"><Pill tone="pill-purple"><BookOpen size={13} /> the expanded Mintify library</Pill><h1>26 lessons. A clearer money brain.</h1><p className="lead">Start with the original beginner course, then wander into everyday money, investing, and market mechanics. Every lesson is short enough to finish and thoughtful enough to remember.</p></div><div className="course-progress"><span>26 lessons</span><span>~4 hours of reading</span><span>Education only—not personal advice</span></div><section className="lesson-gallery" aria-label="Mintify learning themes"><article><img src="/illustrations/money-orbit.jpg" alt="Colorful rupee coins orbiting a notebook" /><div><span>Money basics</span><strong>Make the everyday stuff less mysterious.</strong></div></article><article><img src="/illustrations/safety-net.jpg" alt="A bright safety net catching a phone and coins" /><div><span>Safety first</span><strong>Build habits that protect your money.</strong></div></article><article><img src="/illustrations/market-basket.jpg" alt="A basket holding colorful investment blocks" /><div><span>Investing & markets</span><strong>Understand the machine before the hype.</strong></div></article></section><div className="filters" aria-label="Filter lessons">{[['all', 'All topics'], ['investing', 'Investing'], ['basics', 'Money basics'], ['markets', 'Markets']].map(([key, label]) => <button key={key} className={`filter ${topic === key ? 'is-selected' : ''}`} onClick={() => setTopic(key)}>{label}</button>)}</div><section className="articles" aria-live="polite">{filtered.map((lesson, index) => <article className="article" key={lesson.title}><div className="article-meta"><span>{String(index + 1).padStart(2, '0')}</span>{lesson.meta}</div><div><h2>{lesson.title}</h2><p>{lesson.text}</p></div><a href={`#lesson-${lesson.slug}`}>Read lesson <ArrowUpRight size={16} /></a></article>)}</section></main> }

function Lesson({ slug }) { const lesson = lessonForSlug(slug); if (!lesson) return <Lessons />; const index = courseLessons.findIndex((item) => item.slug === slug); const next = courseLessons[index + 1]; const previous = courseLessons[index - 1]; return <main className="page lesson-page"><a className="back-link" href="#lessons"><ArrowDownRight size={16} /> All lessons</a><header className="lesson-hero"><Pill tone="pill-yellow">Lesson {String(index + 1).padStart(2, '0')} · {lesson.category} · {lesson.minutes} min read</Pill><h1>{lesson.title}</h1><p className="lead">{lesson.standfirst}</p></header><div className="lesson-body">{lesson.sections.map((section, sectionIndex) => <section className="lesson-section" key={section.heading}><div className="section-number">{String(sectionIndex + 1).padStart(2, '0')}</div><div><h2>{section.heading}</h2>{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph}</p>)}{section.terms && <div className="term-grid">{section.terms.map(([term, definition]) => <div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</div>}{section.example && <aside className="lesson-note example"><span>Example</span><p>{section.example}</p></aside>}{section.misconception && <aside className="lesson-note misconception"><span>Common misconception</span><p>{section.misconception}</p></aside>}{section.check && <aside className="check-yourself"><span>Check yourself</span><ol>{section.check.map((question) => <li key={question}>{question}</li>)}</ol></aside>}</div></section>)}</div>{(lesson.slug === 'sips' || lesson.slug === 'compounding') && <section className="lesson-calculator-callout"><div><div className="eyebrow">Put the idea into numbers</div><h2>Try the SIP calculator</h2><p>Compare monthly amounts and timelines. The result is an illustration, not a return promise.</p></div><a className="button" href="#calculator">Open calculator <ArrowUpRight size={16} /></a></section>}<nav className="lesson-next" aria-label="Course navigation">{previous ? <a href={`#lesson-${previous.slug}`}><span>Previous lesson</span>{previous.title} <ArrowDownRight size={16} /></a> : <a href="#lessons"><span>Course shelf</span>View all lessons <ArrowDownRight size={16} /></a>}{next ? <a href={`#lesson-${next.slug}`}><span>Next lesson</span>{next.title} <ArrowUpRight size={16} /></a> : <a href="#lessons"><span>Course complete</span>Back to all lessons <ArrowUpRight size={16} /></a>}</nav></main> }

function Calculator() { const [monthly, setMonthly] = useState(2000); const [rate, setRate] = useState(12); const [years, setYears] = useState(10); const futureValue = useMemo(() => { const months = years * 12; const monthlyRate = rate / 1200; return monthly * ((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate) * (1 + monthlyRate) }, [monthly, rate, years]); const Range = ({ label, value, setValue, min, max, step, suffix = '', money = false }) => <div className="calc-field"><div className="calc-row"><label>{label}</label><output className="calc-value">{money ? `₹${formatINR(value)}` : `${value}${suffix}`}</output></div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={(event) => setValue(Number(event.target.value))} /></div>; return <main className="page"><section className="calculator-layout"><div className="calculator-intro"><Pill tone="pill-yellow"><CalculatorIcon size={13} /> an actual lesson tool</Pill><h1>What might a SIP grow into?</h1><p className="lead">Play with the numbers. The result is an illustration—not a promise—but it is a good way to see how time and consistency work together.</p><div className="formula"><span className="label">Plain-English note</span><p>It assumes you invest the same amount at the end of every month and earn a steady return. Real returns move around.</p></div></div><section className="calculator" aria-label="SIP calculator"><Range label="Monthly amount" value={monthly} setValue={setMonthly} min="500" max="25000" step="500" money /><Range label="Expected annual return" value={rate} setValue={setRate} min="4" max="18" step="1" suffix="%" /><Range label="Time horizon" value={years} setValue={setYears} min="1" max="30" step="1" suffix=" years" /><div className="output"><small>Estimated value after your timeline</small><strong>₹{formatINR(futureValue)}</strong><p>You put in ₹{formatINR(monthly * years * 12)} over {years} years.</p></div><p className="fine-print">This calculator is for education. It uses a simplified monthly-compounding calculation, excludes fees and taxes, and cannot predict real market results.</p></section></section></main> }

function About() { return <main className="page prose"><Pill tone="pill-purple"><Sparkles size={13} /> about mintify</Pill><h1>Money is already in your life. Understanding it should be, too.</h1><p className="lead">Mintify is a learning project for Indian teens who want a useful, calm start with money—not a sales pitch in disguise.</p><ExpandableProfileCardDemo /><h2>Why this exists</h2><p>Financial terms show up early: UPI, savings accounts, IPOs, SIPs, taxes. But the explanations are often written for adults who have already been around them for years. Mintify starts further back, with plain language and one idea at a time.</p><p>The goal is not to tell anyone what to invest in. It is to help readers ask better questions when they eventually need to make a decision.</p><h2>How a lesson gets made</h2><div className="process">{[['01','Begin with a real question','We start from something a person might genuinely wonder, rather than from an industry term that needs to be pushed.'],['02','Remove the assumed knowledge','Every lesson defines what it needs before it uses it. If an example requires a demat account, we explain that first.'],['03','Show the limit','Money decisions carry risk. We say what a tool or idea cannot tell you, especially where actual returns or personal choices are involved.']].map(([number, title, text]) => <div className="process-row" key={number}><div className="label">{number}</div><h3>{title}</h3><p>{text}</p></div>)}</div><h2>A small but important note</h2><p>Mintify is educational material, not financial, investment, tax, or legal advice. Before making a financial decision, speak to a qualified professional and use trustworthy sources.</p></main> }
function Legal({ type }) { const isPrivacy = type === 'privacy'; return <main className="page legal"><Pill tone="pill-yellow">Last updated: 19 September 2026</Pill><h1>{isPrivacy ? 'Privacy policy' : 'Terms of use'}</h1>{isPrivacy ? <><p>This policy explains what information Mintify collects when you use this demonstration site and how it is used.</p><h2>Information we collect</h2><p>The site does not ask you to create an account, submit personal information, or connect a financial account. The SIP calculator runs in your browser; the values you enter are not sent to Mintify.</p><h2>Basic site data</h2><p>If the site is hosted, its hosting provider may automatically receive standard technical information such as browser type, device details, IP address, and pages requested. This information is normally used for security, performance, and aggregate traffic analysis.</p><h2>Cookies</h2><p>This version of Mintify does not set advertising or tracking cookies. A hosting provider may use essential cookies for security or delivery purposes.</p><h2>Changes to this policy</h2><p>If this policy changes, the updated date will appear at the top of this page. Continued use of the site after that change means you accept the updated policy.</p></> : <><p>These terms describe the basic rules for using Mintify. By using the site, you agree to them.</p><h2>For education, not personal advice</h2><p>Mintify provides general educational information. It is not investment, financial, legal, or tax advice, and it is not a recommendation to buy, sell, or hold any investment. Financial decisions should be made with your own research and, where appropriate, a qualified adviser.</p><h2>Calculator results</h2><p>The SIP calculator uses illustrative inputs and a simplified formula. Actual returns may be lower or higher and are not guaranteed. Fees, taxes, inflation, and changes in market conditions can affect real outcomes.</p><h2>Use of content</h2><p>You may read and share links to Mintify for personal, non-commercial learning. Do not present its material as professional advice or reproduce substantial parts of the site without permission.</p><h2>Availability and changes</h2><p>We may update, remove, or correct material at any time. While we aim to keep content clear and accurate, we cannot guarantee that every page is complete, current, or suitable for every situation.</p></>}</main> }

export default function App() { const [page, setPage] = useState(() => window.location.hash.slice(1) || 'home'); useEffect(() => { const update = () => setPage(window.location.hash.slice(1) || 'home'); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update) }, []); useEffect(() => { document.title = page === 'home' ? 'Mintify — money, but make it make sense' : `${page[0].toUpperCase()}${page.slice(1)} | Mintify`; window.scrollTo({ top: 0, behavior: 'smooth' }) }, [page]); const lessonSlug = page.startsWith('lesson-') ? page.slice(7) : null; const screens = { home: <Home />, lessons: <Lessons />, calculator: <Calculator />, about: <About />, privacy: <Legal type="privacy" />, terms: <Legal type="terms" /> }; return <><Header page={lessonSlug ? 'lessons' : page} />{lessonSlug ? <Lesson slug={lessonSlug} /> : (screens[page] ?? screens.home)}<Footer /></> }
